const css=`:host{display:block}ha-card{background:linear-gradient(145deg,#182a30,#101c22);color:#edf3ef;border:1px solid #34474a;border-radius:22px;padding:24px;box-shadow:0 12px 32px #0002}h2{font-size:22px;margin:5px 0 20px;font-weight:500}small,.muted{color:#a6bab9}label{display:block;margin:12px 0 6px}input,select,button{font:inherit;border-radius:10px;padding:10px;border:1px solid #4d6261;background:#21363b;color:#eef4ef;box-sizing:border-box}input{max-width:100%}button{cursor:pointer;background:#d5b77c;color:#15252a;border:0;margin:6px 6px 6px 0}button:disabled{opacity:.5} .row{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:12px 0;border-bottom:1px solid #ffffff10}.row input{width:100px}.value{font-size:23px;color:#e4c58e}.error{color:#ffb4a7}p{line-height:1.5}a{color:#e4c58e}`;
class LuxeControls extends HTMLElement{
 setConfig(c){this.c=c;this.attachShadowIfNeeded()}
 attachShadowIfNeeded(){if(!this.shadowRoot)this.attachShadow({mode:'open'})}
 set hass(h){this.h=h;if(this.shadowRoot.activeElement?.tagName==='INPUT')return;this.render()}
 getCardSize(){return 5}
 render(){if(!this.h||!this.c)return;const root=this.shadowRoot;root.innerHTML=`<style>${css}</style><ha-card><small>GRANT AERONA³ · HEATING</small><h2></h2><div id="rows"></div><p class="muted" id="hint"></p><p class="error" id="error"></p></ha-card>`;root.querySelector('h2').textContent=this.c.title;root.querySelector('#hint').textContent=this.c.hint||'';
 for(const r of this.c.entities){const state=this.h.states[r.entity];const row=document.createElement('div');row.className='row';const label=document.createElement('span');label.textContent=r.name;row.append(label);
 if(state&&!['unknown','unavailable'].includes(state.state)&&['number','input_number'].includes(r.entity.split('.')[0])){const input=document.createElement('input');input.type='number';input.value=state.state;for(const k of ['min','max','step'])if(state.attributes[k]!=null)input[k]=state.attributes[k];input.setAttribute('aria-label',r.name);input.onchange=async()=>{try{await this.h.callService(r.entity.split('.')[0],'set_value',{entity_id:r.entity,value:Number(input.value)});root.querySelector('#error').textContent=''}catch(e){root.querySelector('#error').textContent=e.message||String(e)}};row.append(input)}else{const val=document.createElement('span');val.className='value';val.textContent=state?state.state:'Missing';row.append(val)}root.querySelector('#rows').append(row)} }
}
class LuxeLogger extends HTMLElement{
 setConfig(c){this.c=c;if(!this.shadowRoot)this.attachShadow({mode:'open'})}
 set hass(h){this.h=h;if(!this.started){this.started=true;this.render();this.refresh()}}
 getCardSize(){return 8}
 render(){this.shadowRoot.innerHTML=`<style>${css}input{width:100%}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}@media(max-width:450px){.grid{grid-template-columns:1fr}}</style><ha-card><small>DATA & EXPERIMENTS</small><h2>Record. Compare. Refine.</h2><p id="status">Connecting to logger…</p><div class="grid"><div><label>Sample interval · seconds</label><input id="interval" type="number" min="10" max="3600" value="60"></div><div><label>Retention · days (0 = indefinite)</label><input id="retention" type="number" min="0" max="36500" value="0"></div></div><label><input id="enabled" type="checkbox" checked style="width:auto"> Record data</label><button id="save">Save collection settings</button><button id="refresh">Refresh status</button><p class="muted">State changes are captured as Home Assistant observes them. Sampling cannot improve the heat pump integration’s polling resolution. A finite retention purges older records on subsequent writes.</p><label>Test note · e.g. curve lowered 1°C / comfort unchanged</label><input id="note" maxlength="1000"><button id="mark">Save test note</button><div class="grid"><div><label>Export from</label><input id="from" type="datetime-local"></div><div><label>Export to</label><input id="to" type="datetime-local"></div></div><button id="download">Download CSV</button><button id="all">Download all retained data</button><p id="message" class="muted"></p></ha-card>`;
 const q=id=>this.shadowRoot.querySelector('#'+id);const local=d=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,16)};q('from').value=local(new Date(Date.now()-7*86400000));q('to').value=local(new Date());
 q('refresh').onclick=()=>this.refresh();q('save').onclick=()=>this.act(async()=>{await this.h.callWS({type:'aerona_companion/configure',interval:Number(q('interval').value),retention_days:Number(q('retention').value),enabled:q('enabled').checked});await this.refresh();return 'Collection settings saved.'});q('mark').onclick=()=>this.act(async()=>{await this.h.callWS({type:'aerona_companion/note',note:q('note').value});q('note').value='';return 'Test note recorded.'});q('download').onclick=()=>this.download(false);q('all').onclick=()=>this.download(true); }
 async act(fn){try{this.shadowRoot.querySelector('#message').textContent=await fn()}catch(e){this.shadowRoot.querySelector('#message').textContent=e.message||String(e)}}
 async refresh(){try{const d=await this.h.callWS({type:'aerona_companion/status'});const q=id=>this.shadowRoot.querySelector('#'+id);q('status').textContent=`${d.records.toLocaleString()} records · ${d.settings.enabled?'Recording':'Paused'} · oldest: ${d.first?new Date(d.first*1000).toLocaleString():'none yet'}`;q('interval').value=d.settings.interval;q('retention').value=d.settings.retention_days;q('enabled').checked=d.settings.enabled}catch(e){this.shadowRoot.querySelector('#status').textContent='Companion is not loaded. Check Settings → Devices & services. '+(e.message||'')}}
 async download(all){await this.act(async()=>{const q=id=>this.shadowRoot.querySelector('#'+id);let start=all?0:new Date(q('from').value).getTime()/1000,end=all?Date.now()/1000:new Date(q('to').value).getTime()/1000;if(!Number.isFinite(start)||!Number.isFinite(end)||start>end)throw Error('Choose a valid date range.');const escape=v=>'"'+String(v??'').replaceAll('"','""')+'"';let offset=0,parts=['timestamp_utc,kind,role,entity_id,state,unit,old_state,note\r\n'];for(;;){const rows=await this.h.callWS({type:'aerona_companion/export',start,end,offset});for(const r of rows){const p=r.payload,ts=new Date(r.timestamp*1000).toISOString();let readings=r.kind==='sample'?p:p.readings;if(readings){for(const [role,v]of Object.entries(readings))parts.push([ts,r.kind,role,v.entity_id,v.state,v.unit,p.old,p.note].map(escape).join(',')+'\r\n')}else parts.push([ts,r.kind,'',p.entity_id,p.new,'',p.old,p.note||JSON.stringify(p)].map(escape).join(',')+'\r\n')}offset+=rows.length;q('message').textContent=`Preparing ${offset.toLocaleString()} records…`;if(rows.length<2000)break;}const url=URL.createObjectURL(new Blob(parts,{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='aerona-data-'+new Date().toISOString().slice(0,10)+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);return `Downloaded ${offset.toLocaleString()} records.`})}
}
if(!customElements.get('aerona-luxe-controls'))customElements.define('aerona-luxe-controls',LuxeControls);
if(!customElements.get('aerona-luxe-logger'))customElements.define('aerona-luxe-logger',LuxeLogger);
class AeronaCompanionPanel extends HTMLElement{
 constructor(){super();this.attachShadow({mode:'open'});this.childrenCards=[]}
 set hass(h){this.h=h;for(const c of this.childrenCards)c.hass=h;this.updateBadges();if(!this.started){this.started=true;this.load()}}
 set panel(p){this.panelConfig=p}
 async load(){try{const status=await this.h.callWS({type:'aerona_companion/status'});this.entities=status.entities;this.render();await this.addGraphs()}catch(e){this.shadowRoot.textContent='Aerona Companion could not load: '+(e.message||String(e));this.started=false}}
 render(){const root=this.shadowRoot;root.innerHTML=`<style>${css}:host{height:100%;overflow:auto;background:#0c171c;color:#edf3ef;font-family:var(--paper-font-body1_-_font-family,Arial);display:block}.wrap{max-width:1400px;margin:auto;padding:28px}.eyebrow{color:#d5b77c;letter-spacing:3px;font-size:12px}h1{font-weight:400;font-size:38px;margin:10px 0}.badges{display:flex;gap:10px;flex-wrap:wrap;margin:24px 0}.badge{background:#182a30;border:1px solid #34474a;border-radius:30px;padding:11px 16px;font-size:14px}.badge strong{color:#e4c58e;margin-left:8px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.column{display:flex;flex-direction:column;gap:20px}#graphs{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:20px}button.refresh{float:right}@media(max-width:1050px){.grid{grid-template-columns:1fr 1fr}.column:last-child{grid-column:1/-1}}@media(max-width:650px){.wrap{padding:16px}.grid,#graphs{grid-template-columns:1fr}.column:last-child{grid-column:auto}}</style><div class="wrap"><button class="refresh">Refresh mappings</button><div class="eyebrow">GRANT AERONA³ / HEATING STUDIO</div><h1>Comfort, with clarity.</h1><div class="muted">Live operation · weather compensation · long-term experiments</div><div class="badges"></div><div class="grid"><div class="column" id="curve"></div><div class="column" id="live"></div><div class="column" id="data"></div></div><div id="graphs"></div></div>`;
 root.querySelector('.refresh').onclick=()=>this.load();this.childrenCards=[];
 const control=(container,title,rows,hint)=>{rows=rows.filter(r=>this.entities[r[0]]).map(r=>({entity:this.entities[r[0]],name:r[1]}));if(!rows.length)return;const c=document.createElement('aerona-luxe-controls');c.setConfig({title,entities:rows,hint});c.hass=this.h;root.querySelector(container).append(c);this.childrenCards.push(c)};
 control('#curve','Weather-compensation curve',[['curve_high','2102 · Cold-weather flow'],['curve_low','2103 · Mild-weather flow'],['outdoor_cold','2104 · Cold outdoor endpoint'],['outdoor_warm','2105 · Warm endpoint / cutoff']],'Changes apply when you leave a field. Tariff or forecast automations may overwrite them. The high endpoint is not today’s actual flow target.');
 control('#curve','Tariff adjustments',[['tariff_base','Base curve temperature'],['tariff_boost','Cheap-rate uplift'],['tariff_trim','Peak-rate reduction']],'These are your existing helpers. The companion does not create or alter their automations.');
 control('#live','Live operation',[['compressor','Compressor'],['frequency','Frequency'],['power','Reported power'],['flow','Flow water'],['return','Return water'],['outdoor','Outdoor air'],['defrost','Defrost'],['heating_demand','Heating active'],['dhw_active','Hot-water activity'],['room_ufh','UFH room'],['room_radiators','Radiator room'],['meter_power','Metered power']],'Unknown or unavailable readings are retained as gaps. Reported compressor status is inferred by the Grant integration.');
 const logger=document.createElement('aerona-luxe-logger');logger.setConfig({});logger.hass=this.h;root.querySelector('#data').append(logger);this.childrenCards.push(logger);this.updateBadges(); }
 updateBadges(){const container=this.shadowRoot.querySelector('.badges');if(!container||!this.entities)return;container.replaceChildren();for(const [role,label]of [['outdoor','Outdoor'],['compressor','Compressor'],['power','Power'],['frequency','Frequency'],['flow','Flow'],['return','Return']]){const s=this.h.states[this.entities[role]];const div=document.createElement('div');div.className='badge';div.textContent=label;const strong=document.createElement('strong');strong.textContent=s?(s.state==='on'?'Running':s.state==='off'?'Stopped':s.state)+(s.attributes.unit_of_measurement?' '+s.attributes.unit_of_measurement:''):'Missing';div.append(strong);container.append(div)}}
 async addGraphs(){if(!window.loadCardHelpers)return;try{const helpers=await window.loadCardHelpers();for(const [title,roles]of [['Compressor & defrost · 12 hours',['compressor','defrost']],['Flow, return & outdoor · 24 hours',['flow','return','outdoor']],['Compressor frequency · 24 hours',['frequency']],['Curve changes · 24 hours',['curve_high','curve_low']]]){const entities=roles.map(r=>this.entities[r]).filter(Boolean);if(!entities.length)continue;const card=helpers.createCardElement({type:'history-graph',title,hours_to_show:title.includes('12 hours')?12:24,entities});card.hass=this.h;card.style.cssText='--ha-card-background:#182a30;--primary-text-color:#edf3ef;--secondary-text-color:#a6bab9;--ha-card-border-radius:22px;--ha-card-border-color:#34474a;';this.shadowRoot.querySelector('#graphs').append(card);this.childrenCards.push(card)}}catch(e){const p=document.createElement('p');p.textContent='History charts could not load; logging and export remain available.';this.shadowRoot.querySelector('#graphs').append(p)}}
}
if(!customElements.get('aerona-companion-panel'))customElements.define('aerona-companion-panel',AeronaCompanionPanel);
